on:
- push

name: Build and deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Github Action"
      uses: actions/checkout@v4
    
    - name: "Docker login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}    
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: "Image build and push"
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/ecommerce:${{ github.sha }}
    
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: example-web-app-codeseoul-beege
        images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/ecommerce:${{ github.sha }}
        publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}